config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "welcome#index"

  resources :users

  get "/follow/:id" => "users#follow", as: :follow
  get "/unfollow/:id" => "users#unfollow", as: :unfollow

  post "/messages" => "messages#create", as: :messages

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  default_scope { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages

  has_one_attached :avatar

  serialize :following, Array

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   attributes = [:username, :first_name, :last_name, :location, :bio, :avatar]
   devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
   devise_parameter_sanitizer.permit(:account_update, keys: attributes)
 end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    message = current_user.messages.new(message_params)

    if message.save
      redirect_to user_url(id: current_user.id)
    else
      #insert error path here
    end

  end


  private

  def message_params
    params.require(:message).permit(:body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all - [current_user]
  end

  def show
    @user = User.find(params[:id])
    @message = Message.new

    if current_user == @user
      following_ids = current_user.following
      following_ids << current_user.id
      @messages = Message.where(user_id: current_user.following)
    else
      @messages = @user.messages
    end
  end

    def follow
      @user = User.find(params[:id])
      current_user.following << @user.id
      current_user.save
      redirect_to user_url(id: @user.id), notice: "Now following user @#{@user.username}"
  end

    def unfollow
      @user = User.find(params[:id])
      current_user.following.delete(@user.id)
      current_user.save
      redirect_to user_url(id: @user.id), notice: "Successfully unfollowed user @#{@user.username}"
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_user
      redirect_to user_url(id: current_user.id)
    else
      render 'index'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <%= link_to "Home", root_url %>
      <% if current_user %>
      <%= link_to "User Profile", edit_user_registration_url %>
      <%= link_to "Users", users_url %>
      <%= link_to "Logout", destroy_user_session_url, method: 'delete' %>
      <% else %>
      <%= link_to "Login", new_user_session_url %>
      <% end %>
    </nav>
    <div class="container">
      <% if notice  %>
        <p class="notice alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
  <div class="user card">
  <%= image_tag url_for(user.avatar), width: '75px' %>
  <br />
  <%= link_to "@#{user.username}", user_url(id: user.id) %>
  </div>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class = "left_side" id="left_side_div">

  <%= image_tag url_for(@user.avatar), width: '75px' %>
  <br />
  @<%= @user.username %>
  <br />
  <%= @user.full_name %>
  <br />
  <%= @user.location %>
  <br />
  <br />
  <%= @user.bio %>
  <br />
  <br />
  <% unless @user == current_user  %>
    <% if current_user.following.include?(@user.id)  %>
      <%= link_to "Unfollow", unfollow_url(id: @user.id), class: 'btn btn-danger', id: 'unfollow_btn' %>
      <%= link_to "Follow", follow_url(id: @user.id), class: 'btn btn-primary', id: 'follow_btn', style: "display:none;" %>
    <% else  %>
      <%= link_to "Follow", follow_url(id: @user.id), class: 'btn btn-primary', id: 'follow_btn' %>
      <%= link_to "Unfollow", unfollow_url(id: @user.id), class: 'btn btn-danger', id: 'unfollow_btn', style: "display: none;" %>
    <% end %>
  <% end  %>
</div>

<div class = "right_side">
  <% if current_user == @user %>
    <%= form_for @message do |f| %>
      <div class="field">
        <%= f.label :body %>
        <br />
        <%= f.text_area :body %>
      </div>
      <br />
      <div class="field">
        <%= f.submit "Send Message", class: 'btn btn-primary float-right', id: 'create_tweet_btn' %>
      </div>
      <br />
      <br />
      <br />
    <% end %>
  <% end %>
  <% @messages.each do |message| %>
    <div class = "tweet">
      <%= image_tag url_for(message.user.avatar), width: '20px' %>
      <p class="tweet-body"><%= message.body %></p>
      <p class="tweet-date">Posted <%= time_ago_in_words(message.created_at) %> ago </p>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to Twitter</h1>